services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: recipe_tracker
      POSTGRES_USER: recipe_tracker
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_tracker -d recipe_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
